name: Start Minecraft Server
on:
  workflow_dispatch: # Allows manual execution

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make start.sh executable
        run: chmod +x start.sh

      - name: Run start.sh
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: ./start.sh

      - name: Backup Server Data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-save server data"
          git push https://${{ secrets.GH_PAT }}@github.com/Breath34/test.git
