name: Start Minecraft Server
on: push

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Make start.sh executable
        run: chmod +x start.sh
        
      - name: Run start.sh
        run: ./start.sh
